### ISSUE TITLE
Request: Add Update Order Method

### ISSUE THREAD

**Issue by benhamlett** [Wingly-Company/pwinty#6]
currently we can only use 
`
$user = User::first();

$user->newOrder()
    ->setRecipientName('John Doe')
    ->setCountryCode('FR')
    ->create();
`

It would be fantastic if we could update an existing order using the API too.

**Comment by gpanos** [comment]
@benhamlett makes sense. I will try to find some time soon to add this should be fairly easy. 
PRs are always welcomed :) 
Thanks

**Comment by benhamlett** [comment]
@gpanos Cheers mate,
I think the only issue I am having with this atm is that there is no way to do a newOrder() if you have extra fields on the table that are not nullable. currently our process is create the order locally and on approve we want to create the order on Pwinty. So even a method in the OrderBuilder to create the Pwinty order and only update the pwinty_id & pwinty_status only would be great :)

**Comment by gpanos** [comment]
@benhamlett tagged a new release that provides a `updatePwintyOrder`  method. https://github.com/Wingly-Company/pwinty#updating-an-order.
